INSERT INTO airports.countries (code,name,continent) VALUES
	 ('AO','Angola','AF'),
	 ('BF','Burkina Faso','AF'),
	 ('BI','Burundi','AF'),
	 ('BJ','Benin','AF'),
	 ('BW','Botswana','AF'),
	 ('CD','Congo (Kinshasa)','AF'),
	 ('CF','Central African Republic','AF'),
	 ('CG','Congo (Brazzaville)','AF'),
	 ('CI','Côte d''Ivoire','AF'),
	 ('CM','Cameroon','AF');
INSERT INTO airports.countries (code,name,continent) VALUES
	 ('CV','Cape Verde','AF'),
	 ('DJ','Djibouti','AF'),
	 ('DZ','Algeria','AF'),
	 ('EG','Egypt','AF'),
	 ('EH','Western Sahara','AF'),
	 ('ER','Eritrea','AF'),
	 ('ET','Ethiopia','AF'),
	 ('GA','Gabon','AF'),
	 ('GH','Ghana','AF'),
	 ('GM','Gambia','AF');
INSERT INTO airports.countries (code,name,continent) VALUES
	 ('GN','Guinea','AF'),
	 ('GQ','Equatorial Guinea','AF'),
	 ('GW','Guinea-Bissau','AF'),
	 ('KE','Kenya','AF'),
	 ('KM','Comoros','AF'),
	 ('LR','Liberia','AF'),
	 ('LS','Lesotho','AF'),
	 ('LY','Libya','AF'),
	 ('MA','Morocco','AF'),
	 ('MG','Madagascar','AF');
INSERT INTO airports.countries (code,name,continent) VALUES
	 ('ML','Mali','AF'),
	 ('MR','Mauritania','AF'),
	 ('MU','Mauritius','AF'),
	 ('MW','Malawi','AF'),
	 ('MZ','Mozambique','AF'),
	 ('NA','Namibia','AF'),
	 ('NE','Niger','AF'),
	 ('NG','Nigeria','AF'),
	 ('RE','Réunion','AF'),
	 ('RW','Rwanda','AF');
INSERT INTO airports.countries (code,name,continent) VALUES
	 ('SC','Seychelles','AF'),
	 ('SD','Sudan','AF'),
	 ('SH','Saint Helena','AF'),
	 ('SL','Sierra Leone','AF'),
	 ('SN','Senegal','AF'),
	 ('SO','Somalia','AF'),
	 ('ST','São Tomé and Principe','AF'),
	 ('SZ','Swaziland','AF'),
	 ('TD','Chad','AF'),
	 ('TG','Togo','AF');
INSERT INTO airports.countries (code,name,continent) VALUES
	 ('TN','Tunisia','AF'),
	 ('TZ','Tanzania','AF'),
	 ('UG','Uganda','AF'),
	 ('YT','Mayotte','AF'),
	 ('ZA','South Africa','AF'),
	 ('ZM','Zambia','AF'),
	 ('ZW','Zimbabwe','AF'),
	 ('ZZ','Unknown or unassigned country','AF'),
	 ('SS','South Sudan','AF'),
	 ('AQ','Antarctica','AN');
INSERT INTO airports.countries (code,name,continent) VALUES
	 ('GS','South Georgia and the South Sandwich Islands','AN'),
	 ('TF','French Southern Territories','AN'),
	 ('AE','United Arab Emirates','AS'),
	 ('AF','Afghanistan','AS'),
	 ('AM','Armenia','AS'),
	 ('AZ','Azerbaijan','AS'),
	 ('BD','Bangladesh','AS'),
	 ('BH','Bahrain','AS'),
	 ('BN','Brunei','AS'),
	 ('BT','Bhutan','AS');
INSERT INTO airports.countries (code,name,continent) VALUES
	 ('CC','Cocos (Keeling) Islands','AS'),
	 ('CN','China','AS'),
	 ('CX','Christmas Island','AS'),
	 ('CY','Cyprus','AS'),
	 ('GE','Georgia','AS'),
	 ('HK','Hong Kong','AS'),
	 ('ID','Indonesia','AS'),
	 ('IL','Israel','AS'),
	 ('IN','India','AS'),
	 ('IO','British Indian Ocean Territory','AS');
INSERT INTO airports.countries (code,name,continent) VALUES
	 ('IQ','Iraq','AS'),
	 ('IR','Iran','AS'),
	 ('JO','Jordan','AS'),
	 ('JP','Japan','AS'),
	 ('KG','Kyrgyzstan','AS'),
	 ('KH','Cambodia','AS'),
	 ('KP','North Korea','AS'),
	 ('KR','South Korea','AS'),
	 ('KW','Kuwait','AS'),
	 ('KZ','Kazakhstan','AS');
INSERT INTO airports.countries (code,name,continent) VALUES
	 ('LA','Laos','AS'),
	 ('LB','Lebanon','AS'),
	 ('LK','Sri Lanka','AS'),
	 ('MM','Burma','AS'),
	 ('MN','Mongolia','AS'),
	 ('MO','Macau','AS'),
	 ('MV','Maldives','AS'),
	 ('MY','Malaysia','AS'),
	 ('NP','Nepal','AS'),
	 ('OM','Oman','AS');
INSERT INTO airports.countries (code,name,continent) VALUES
	 ('PH','Philippines','AS'),
	 ('PK','Pakistan','AS'),
	 ('PS','Palestinian Territory','AS'),
	 ('QA','Qatar','AS'),
	 ('SA','Saudi Arabia','AS'),
	 ('SG','Singapore','AS'),
	 ('SY','Syria','AS'),
	 ('TH','Thailand','AS'),
	 ('TJ','Tajikistan','AS'),
	 ('TL','Timor-Leste','AS');
INSERT INTO airports.countries (code,name,continent) VALUES
	 ('TM','Turkmenistan','AS'),
	 ('TR','Turkey','AS'),
	 ('TW','Taiwan','AS'),
	 ('UZ','Uzbekistan','AS'),
	 ('VN','Vietnam','AS'),
	 ('YE','Yemen','AS'),
	 ('AD','Andorra','EU'),
	 ('AL','Albania','EU'),
	 ('AT','Austria','EU'),
	 ('BA','Bosnia and Herzegovina','EU');
INSERT INTO airports.countries (code,name,continent) VALUES
	 ('BE','Belgium','EU'),
	 ('BG','Bulgaria','EU'),
	 ('BY','Belarus','EU'),
	 ('CH','Switzerland','EU'),
	 ('CZ','Czech Republic','EU'),
	 ('DE','Germany','EU'),
	 ('DK','Denmark','EU'),
	 ('EE','Estonia','EU'),
	 ('ES','Spain','EU'),
	 ('FI','Finland','EU');
INSERT INTO airports.countries (code,name,continent) VALUES
	 ('FO','Faroe Islands','EU'),
	 ('FR','France','EU'),
	 ('GB','United Kingdom','EU'),
	 ('GG','Guernsey','EU'),
	 ('GI','Gibraltar','EU'),
	 ('GR','Greece','EU'),
	 ('HR','Croatia','EU'),
	 ('HU','Hungary','EU'),
	 ('IE','Ireland','EU'),
	 ('IM','Isle of Man','EU');
INSERT INTO airports.countries (code,name,continent) VALUES
	 ('IS','Iceland','EU'),
	 ('IT','Italy','EU'),
	 ('JE','Jersey','EU'),
	 ('LI','Liechtenstein','EU'),
	 ('LT','Lithuania','EU'),
	 ('LU','Luxembourg','EU'),
	 ('LV','Latvia','EU'),
	 ('MC','Monaco','EU'),
	 ('MD','Moldova','EU'),
	 ('ME','Montenegro','EU');
INSERT INTO airports.countries (code,name,continent) VALUES
	 ('MK','Macedonia','EU'),
	 ('MT','Malta','EU'),
	 ('NL','Netherlands','EU'),
	 ('NO','Norway','EU'),
	 ('PL','Poland','EU'),
	 ('PT','Portugal','EU'),
	 ('RO','Romania','EU'),
	 ('RS','Serbia','EU'),
	 ('RU','Russia','EU'),
	 ('SE','Sweden','EU');
INSERT INTO airports.countries (code,name,continent) VALUES
	 ('SI','Slovenia','EU'),
	 ('SK','Slovakia','EU'),
	 ('SM','San Marino','EU'),
	 ('UA','Ukraine','EU'),
	 ('XK','Kosovo','EU'),
	 ('VA','Vatican City','EU'),
	 ('AG','Antigua and Barbuda','NA'),
	 ('AI','Anguilla','NA'),
	 ('BQ','Caribbean Netherlands','NA'),
	 ('AW','Aruba','NA');
INSERT INTO airports.countries (code,name,continent) VALUES
	 ('BB','Barbados','NA'),
	 ('BM','Bermuda','NA'),
	 ('BS','Bahamas','NA'),
	 ('BZ','Belize','NA'),
	 ('CA','Canada','NA'),
	 ('CR','Costa Rica','NA'),
	 ('CU','Cuba','NA'),
	 ('DM','Dominica','NA'),
	 ('DO','Dominican Republic','NA'),
	 ('GD','Grenada','NA');
INSERT INTO airports.countries (code,name,continent) VALUES
	 ('GL','Greenland','NA'),
	 ('GP','Guadeloupe','NA'),
	 ('GT','Guatemala','NA'),
	 ('HN','Honduras','NA'),
	 ('HT','Haiti','NA'),
	 ('JM','Jamaica','NA'),
	 ('KN','Saint Kitts and Nevis','NA'),
	 ('KY','Cayman Islands','NA'),
	 ('LC','Saint Lucia','NA'),
	 ('MQ','Martinique','NA');
INSERT INTO airports.countries (code,name,continent) VALUES
	 ('MS','Montserrat','NA'),
	 ('MX','Mexico','NA'),
	 ('NI','Nicaragua','NA'),
	 ('PA','Panama','NA'),
	 ('PM','Saint Pierre and Miquelon','NA'),
	 ('PR','Puerto Rico','NA'),
	 ('SV','El Salvador','NA'),
	 ('TC','Turks and Caicos Islands','NA'),
	 ('TT','Trinidad and Tobago','NA'),
	 ('US','United States','NA');
INSERT INTO airports.countries (code,name,continent) VALUES
	 ('VC','Saint Vincent and the Grenadines','NA'),
	 ('VG','British Virgin Islands','NA'),
	 ('VI','U.S. Virgin Islands','NA'),
	 ('MF','Saint Martin','NA'),
	 ('BL','Saint Barthélemy','NA'),
	 ('SX','Sint Maarten','NA'),
	 ('CW','Curaçao','NA'),
	 ('AS','American Samoa','OC'),
	 ('AU','Australia','OC'),
	 ('CK','Cook Islands','OC');
INSERT INTO airports.countries (code,name,continent) VALUES
	 ('FJ','Fiji','OC'),
	 ('FM','Micronesia','OC'),
	 ('GU','Guam','OC'),
	 ('KI','Kiribati','OC'),
	 ('MH','Marshall Islands','OC'),
	 ('MP','Northern Mariana Islands','OC'),
	 ('NC','New Caledonia','OC'),
	 ('NF','Norfolk Island','OC'),
	 ('NR','Nauru','OC'),
	 ('NU','Niue','OC');
INSERT INTO airports.countries (code,name,continent) VALUES
	 ('NZ','New Zealand','OC'),
	 ('PF','French Polynesia','OC'),
	 ('PG','Papua New Guinea','OC'),
	 ('PN','Pitcairn','OC'),
	 ('PW','Palau','OC'),
	 ('SB','Solomon Islands','OC'),
	 ('TK','Tokelau','OC'),
	 ('TO','Tonga','OC'),
	 ('TV','Tuvalu','OC'),
	 ('UM','United States Minor Outlying Islands','OC');
INSERT INTO airports.countries (code,name,continent) VALUES
	 ('VU','Vanuatu','OC'),
	 ('WF','Wallis and Futuna','OC'),
	 ('WS','Samoa','OC'),
	 ('AR','Argentina','SA'),
	 ('BO','Bolivia','SA'),
	 ('BR','Brazil','SA'),
	 ('CL','Chile','SA'),
	 ('CO','Colombia','SA'),
	 ('EC','Ecuador','SA'),
	 ('FK','Falkland Islands','SA');
INSERT INTO airports.countries (code,name,continent) VALUES
	 ('GF','French Guiana','SA'),
	 ('GY','Guyana','SA'),
	 ('PE','Perú','SA'),
	 ('PY','Paraguay','SA'),
	 ('SR','Suriname','SA'),
	 ('UY','Uruguay','SA'),
	 ('VE','Venezuela','SA');